# References
https://scikit-learn.org/stable/modules/tree.html
    

In [1]:
# Import Libraries
import pandas as pd
import numpy as np

In [2]:
# Input data
from sklearn.datasets import load_iris
iris = load_iris()
X, y = iris.data, iris.target

In [3]:
# Split Data
## Closed test
X_train, X_test, y_train, y_test = X, X, y, y

## Open test


In [4]:
# Modeling
from sklearn import tree
clf = tree.DecisionTreeClassifier() 
clf = clf.fit(X_train, y_train)

In [5]:
# Prediction
y_pred = clf.predict(X_test)

In [6]:
# Evaluation
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, y_pred)
print(conf_mat)

[[50  0  0]
 [ 0 50  0]
 [ 0  0 50]]


In [7]:
# Visualize Model - plot_tree
tree.plot_tree(clf) 

[Text(248.0, 338.79999999999995, 'X[2] <= 2.45\nentropy = 0.667\nsamples = 150\nvalue = [50, 50, 50]'),
 Text(209.84615384615384, 277.2, 'entropy = 0.0\nsamples = 50\nvalue = [50, 0, 0]'),
 Text(286.15384615384613, 277.2, 'X[3] <= 1.75\nentropy = 0.5\nsamples = 100\nvalue = [0, 50, 50]'),
 Text(152.6153846153846, 215.59999999999997, 'X[2] <= 4.95\nentropy = 0.168\nsamples = 54\nvalue = [0, 49, 5]'),
 Text(76.3076923076923, 154.0, 'X[3] <= 1.65\nentropy = 0.041\nsamples = 48\nvalue = [0, 47, 1]'),
 Text(38.15384615384615, 92.39999999999998, 'entropy = 0.0\nsamples = 47\nvalue = [0, 47, 0]'),
 Text(114.46153846153845, 92.39999999999998, 'entropy = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(228.9230769230769, 154.0, 'X[3] <= 1.55\nentropy = 0.444\nsamples = 6\nvalue = [0, 2, 4]'),
 Text(190.76923076923077, 92.39999999999998, 'entropy = 0.0\nsamples = 3\nvalue = [0, 0, 3]'),
 Text(267.0769230769231, 92.39999999999998, 'X[2] <= 5.45\nentropy = 0.444\nsamples = 3\nvalue = [0, 2, 1]'),
 Tex

In [8]:
# Visualize Model - plot_tree
from sklearn.tree.export import export_text 
r = export_text(clf, feature_names=iris['feature_names'])
print(r)

|--- petal length (cm) <= 2.45
|   |--- class: 0
|--- petal length (cm) >  2.45
|   |--- petal width (cm) <= 1.75
|   |   |--- petal length (cm) <= 4.95
|   |   |   |--- petal width (cm) <= 1.65
|   |   |   |   |--- class: 1
|   |   |   |--- petal width (cm) >  1.65
|   |   |   |   |--- class: 2
|   |   |--- petal length (cm) >  4.95
|   |   |   |--- petal width (cm) <= 1.55
|   |   |   |   |--- class: 2
|   |   |   |--- petal width (cm) >  1.55
|   |   |   |   |--- petal length (cm) <= 5.45
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- petal length (cm) >  5.45
|   |   |   |   |   |--- class: 2
|   |--- petal width (cm) >  1.75
|   |   |--- petal length (cm) <= 4.85
|   |   |   |--- sepal length (cm) <= 5.95
|   |   |   |   |--- class: 1
|   |   |   |--- sepal length (cm) >  5.95
|   |   |   |   |--- class: 2
|   |   |--- petal length (cm) >  4.85
|   |   |   |--- class: 2

