# References
- https://scikit-learn.org/stable/modules/tree.html

# Memo
- sklearnのtreeはCARTを使っているらしい

In [1]:
# Import Libraries
import pandas as pd
import numpy as np

In [2]:
# Input data
from sklearn.datasets import load_iris
iris = load_iris()
X, y = iris.data, iris.target

In [3]:
# Split Data
## Closed test
X_train, X_test, y_train, y_test = X, X, y, y

## Open test


In [9]:
# Modeling
from sklearn import tree
clf = tree.DecisionTreeClassifier(max_depth = 2) 
clf = clf.fit(X_train, y_train)

In [10]:
# Prediction
y_pred = clf.predict(X_test)

In [11]:
# Evaluation
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, y_pred)
print(conf_mat)

[[50  0  0]
 [ 0 49  1]
 [ 0  5 45]]


In [12]:
# Visualize Model - plot_tree
tree.plot_tree(clf) 

[Text(133.92000000000002, 181.2, 'X[3] <= 0.8\nentropy = 0.667\nsamples = 150\nvalue = [50, 50, 50]'),
 Text(66.96000000000001, 108.72, 'entropy = 0.0\nsamples = 50\nvalue = [50, 0, 0]'),
 Text(200.88000000000002, 108.72, 'X[3] <= 1.75\nentropy = 0.5\nsamples = 100\nvalue = [0, 50, 50]'),
 Text(133.92000000000002, 36.23999999999998, 'entropy = 0.168\nsamples = 54\nvalue = [0, 49, 5]'),
 Text(267.84000000000003, 36.23999999999998, 'entropy = 0.043\nsamples = 46\nvalue = [0, 1, 45]')]

In [8]:
# Visualize Model - plot_tree
from sklearn.tree.export import export_text 
r = export_text(clf, feature_names=iris['feature_names'])
print(r)

|--- petal length (cm) <= 2.45
|   |--- class: 0
|--- petal length (cm) >  2.45
|   |--- petal width (cm) <= 1.75
|   |   |--- petal length (cm) <= 4.95
|   |   |   |--- class: 1
|   |   |--- petal length (cm) >  4.95
|   |   |   |--- class: 2
|   |--- petal width (cm) >  1.75
|   |   |--- petal length (cm) <= 4.85
|   |   |   |--- class: 2
|   |   |--- petal length (cm) >  4.85
|   |   |   |--- class: 2

