# References
- https://scikit-learn.org/stable/modules/tree.html

# Memo
- sklearnのtreeはCARTを使っているらしい

In [1]:
# Import Libraries
import pandas as pd
import numpy as np

In [2]:
# Input data
from sklearn.datasets import load_iris
iris = load_iris()
X, y = iris.data, iris.target

In [3]:
# Split Data
## Closed test
X_train, X_test, y_train, y_test = X, X, y, y

## Open test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=335)

In [4]:
# Modeling
from sklearn import tree
clf = tree.DecisionTreeClassifier(max_depth = 2) 
clf = clf.fit(X_train, y_train)

In [5]:
# Prediction
y_pred = clf.predict(X_test)

In [6]:
# Evaluation
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, y_pred)
print(conf_mat)

[[10  0  0]
 [ 0 12  0]
 [ 0  1  7]]


In [7]:
# Visualize Model - plot_tree
tree.plot_tree(clf) 

[Text(198.4, 308.0, 'X[2] <= 2.6\nentropy = 0.666\nsamples = 120\nvalue = [40, 38, 42]'),
 Text(99.2, 184.79999999999998, 'entropy = 0.0\nsamples = 40\nvalue = [40, 0, 0]'),
 Text(297.6, 184.79999999999998, 'X[3] <= 1.75\nentropy = 0.499\nsamples = 80\nvalue = [0, 38, 42]'),
 Text(198.4, 61.599999999999966, 'entropy = 0.176\nsamples = 41\nvalue = [0, 37, 4]'),
 Text(396.8, 61.599999999999966, 'entropy = 0.05\nsamples = 39\nvalue = [0, 1, 38]')]

In [8]:
# Visualize Model - plot_tree
from sklearn.tree.export import export_text 
r = export_text(clf, feature_names=iris['feature_names'])
print(r)

|--- petal length (cm) <= 2.60
|   |--- class: 0
|--- petal length (cm) >  2.60
|   |--- petal width (cm) <= 1.75
|   |   |--- class: 1
|   |--- petal width (cm) >  1.75
|   |   |--- class: 2

